jobs:
  build:
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    steps:
      - checkout
      - run: echo "this is the test job"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
